server:
  port: 8081

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8001
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        - id: core-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/core/**
          filters:
            - StripPrefix=1

        - id: ai-place-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/ai/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka