server:
  port: 8001

spring:
  application:
    name: AUTH-SERVICE

  datasource:
    url: jdbc:h2:mem:authdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: ${JWT_SECRET:j9DJrShbo8zent0ckOlpw5vayQMIdH3ZEiX4NLVB1CPK7AxqYfgmGU6uFRTsW2}
  accessTokenExpirationMs: 3600000
  refreshTokenExpirationMs: 86400000
